version: '3'

services:
  faucet:
    build: .
    restart: always
    stdin_open: true
    tty: true
    command: sh -c "yarn start:dev"
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 9229:9229

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: faucet
    volumes:
      - ./.mongo/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: --profile=1 --slowms=20 # for operations that take longer than (ms)

  mongo-test:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: faucet-test
    volumes:
      - ./mongo-init-test.js:/docker-entrypoint-initdb.d/mongo-init-test.js
    command: --profile=1 --slowms=20 # for operations that take longer than (ms)
