version: '3'

services:
  faucet:
    build: .
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 3000:3000

  mongo:
    image: mongo
    volumes:
      - ./.mongo/db:/data/db
    command: --profile=1 --slowms=20 # for operations that take longer than (ms)
