version: '3'

services:
  faucet:
    build: .
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 3000:3000

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: faucet
    volumes:
      - ./.mongo/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: --profile=1 --slowms=20 # for operations that take longer than (ms)
