version: '3'

services:
  faucet:
    image: asia.gcr.io/firovm-faucet/firovm-faucet:0.0.1
    volumes:
      - ./.env:/app/.env
    depends_on:
      - mongo
      - firovm

  mongo:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: faucet
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: --profile=1 --slowms=20 # for operations that take longer than (ms)

  e2e-test:
    image: asia.gcr.io/firovm-faucet/firovm-faucet:0.0.1
    command: yarn test:e2e
    volumes:
      - ./.env:/app/.env
    depends_on:
      - faucet

  firovm:
    image: satangtech/firovm-poa:9139c0a7560a8e03be0852c33b94acefcfc4887b
    tty: true
    stdin_open: true
    command: bash -c "tar xfv firovm.tar && firovmd"
    volumes:
      - ./firovm.tar:/home/firovm/firovm.tar
    ports:
      - 1234:1234
      - 11000:11000
