version: '3'

services:
  faucet:
    build: .
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./app/tokens.json:/app/tokens.json
    ports:
      - 8123:8123
      - 9229:9229

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./.mongo/db:/data/db
    command: --profile=1 --slowms=20 # for operations that take longer than (ms)
